title: Relaton
description: Interoperable data models for citations
# The above two are used by jekyll-seo-tag for things such as
# `<title>` and `<meta>` tags, as well as elsewhere by the theme.

permalink: /blog/:year-:month-:day-:title/

url: https://www.relaton.org
github_repo_url: https://github.com/relaton/relaton.github.io
github_repo_branch: main
permalink: /blog/:year-:month-:day-:title/

algolia_search:
  api_key: '31ca4bad475130bdaee582a0b9f40806'
  index_name: 'metanorma'

tagline: >-
  Interoperable data&nbsp;model for&nbsp;citations
  based&nbsp;on&nbsp;ISO&nbsp;690

landing_priority: [custom_intro, blog, specs, software]

theme: jekyll-theme-open-project

relaton:

  supported_bibliographies:
    - id: iso
      label: ISO
      citation_guide: true
      gem: relaton-iso
      sources:
        - { url: "https://www.iso.org", label: "International Organization for Standardization" }
    - id: iec
      label: IEC
      citation_guide: true
      gem: relaton-iec
      sources:
        - { url: "https://www.iec.ch", label: "International Electrotechnical Commission" }
    - id: itu
      label: ITU-T & ITU-R
      citation_guide: false
      gem: relaton-itu
      sources:
        - { url: "https://www.itu.int", label: "International Telecommunication Union" }
    - id: ietf
      label: RFC & I-D (IETF)
      citation_guide: true
      gem: relaton-ietf
      sources:
        - { url: "https://bib.ietf.org", label: "Internet Engineering Task Force" }
    - id: ieee
      label: IEEE
      citation_guide: true
      gem: relaton-ieee
      sources:
        - { url: "https://standards.ieee.org", label: "IEEE Standards Association" }
    - id: nist
      label: NIST
      citation_guide: false
      gem: relaton-nist
      sources:
        - { url: "https://www.nist.gov", label: "National Institute of Standards and Technology" }
    - id: bipm
      label: BIPM
      citation_guide: true
      gem: relaton-bipm
      sources:
        - { url: "https://www.bipm.org", label: "International Bureau of Weights and Measures" }
    - id: 3gpp
      label: 3GPP
      citation_guide: true
      gem: relaton-3gpp
      sources:
        - { url: "https://www.3gpp.org", label: "3rd Generation Partnership Project" }
    - id: ogc
      label: OGC
      citation_guide: false
      gem: relaton-ogc
      sources:
        - { url: "https://www.ogc.org", label: "Open Geospatial Consortium" }
    - id: iev
      label: IEC Electropedia (IEV)
      citation_guide: false
      gem: relaton-iev
      sources:
        - { url: "https://www.electropedia.org", label: "IEC Electropedia" }
    - id: oasis
      label: OASIS
      citation_guide: false
      gem: relaton-oasis
      sources:
        - { url: "https://www.oasis-open.org/standards/", label: "OASIS OPEN"}
    - id: cie
      label: CIE
      citation_guide: true
      gem: relaton-cie
      sources:
        - { url: "https://cie.co.at", label: "International Commission on Illumination" }
    - id: w3c
      label: W3C
      citation_guide: false
      gem: relaton-w3c
      sources:
        - { url: "https://www.w3.org", label: "World Wide Web Consortium" }
    - id: ecma
      label: Ecma
      citation_guide: true
      gem: relaton-ecma
      sources:
        - { url: "https://www.ecma-international.org", label: "Ecma International" }
    - id: iho
      label: IHO
      gem: relaton-iho
      citation_guide: false
      sources:
        - { url: "https://www.iho.int", label: "International Hydrographic Organization" }
    - id: omg
      label: OMG
      citation_guide: false
      gem: relaton-omg
      sources:
        - { url: "https://www.omg.org", label: "Object Management Group" }
    - id: un
      label: UN Docs
      citation_guide: false
      gem: relaton-un
      sources:
        - { url: "https://documents.un.org", label: "UN Official Document System" }
    - id: cen
      label: EN (CEN/CENELEC)
      citation_guide: true
      gem: relaton-cen
      sources:
        - { url: "https://standards.cen.eu", label: "CEN/CENELEC" }
    - id: bsi
      label: BS, PAS (BSI)
      citation_guide: true
      gem: relaton-bsi
      sources:
        - { url: "https://www.bsigroup.com", label: "British Standards Institution" }
    - id: jis
      label: JIS (JSA)
      citation_guide: false
      gem: relaton-jis
      sources:
        - { url: "https://webdesk.jsa.or.jp", label: "Japanese Standards Association" }
    - id: gb
      label: GB
      citation_guide: true
      gem: relaton-gb
      sources:
        - { label: "Chinese National Standards" }
    - id: calconnect
      label: CalConnect
      citation_guide: true
      gem: relaton-calconnect
      sources:
        - { url: "https://www.calconnect.org", label: "CalConnect" }
    - id: ccsds
      label: CCSDS
      citation_guide: true
      gem: relaton-ccsds
      sources:
        - { url: "https://public.ccsds.org", label: "Consultative Committee for Space Data Systems" }
    - id: iana
      label: IANA
      citation_guide: true
      gem: relaton-iana
      sources:
        - { url: "https://www.iana.org", label: "Internet Assigned Numbers Authority" }
    - id: xsf
      label: XSF
      citation_guide: false
      gem: relaton-xsf
      sources:
        - { url: "https://xmpp.org/extensions/", label: "XMPP Standards Foundation" }
    - id: doi
      label: DOI
      citation_guide: false
      gem: relaton-doi
      sources:
        - { url: "https://www.crossref.org/documentation/retrieve-metadata/rest-api/", label: "Digital Object Identifier" }

author:
  name: Ribose Inc.
  url: https://www.ribose.com

authors:
  - name: Ribose Inc.
    email: open.source@ribose.com

contact_email: open.source@ribose.com

theme: jekyll-theme-open-project

parent_hub:
  git_repo_url: https://github.com/riboseinc/open.ribose.com
  git_repo_branch: main
  home_url: https://open.ribose.com/

includes_dir: '.'

social:
  links:
    - https://twitter.com/RiboseUS
    - https://github.com/relaton/relaton

legal:
  name: Ribose Group Inc.
  tos_link: https://www.ribose.com/tos
  privacy_policy_link: https://www.ribose.com/privacy

home_calls_to_action:
  - { url: "/blog/", title: "Blog" }
  - { url: "/software/relaton/docs/README/", title: "Using the gem" }
  #- { url: "/software/relaton-cli/docs/README/", title: "Using the CLI" }

collections:
  projects:
    output: false
  software:
    output: true
    permalink: /software/:path/
  specs:
    output: true
    permalink: /specs/:path/
  posts:
    output: true
    permalink: /blog/:year-:month-:day-:title/
  pages:
    output: true
    permalink: /:name/
  cite_docs:
    output: true
    permalink: /cite/:path/


defaults:
  # Theme defaults.
  # MUST be duplicated from themeâ€™s _config.yml
  # (does not get inherited, unlike the collections hash)
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
  - scope:
      path: _software
      type: software
    values:
      layout: product
  - scope:
      path: _specs
      type: specs
    values:
      layout: spec

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

tag_namespaces:
  software:
    writtenin: "Written in"
    bindingsfor: "Bindings for"
    user: "Target user"
    interface: "Interface"
  specs:
    audience: "Audience"
    completion_status: "Status"

include:
  - "index.adoc"
  - "404.html"

exclude:
  - .git
  - .lycheeignore
  - "*/.git"
  - Gemfile*
  - Makefile
  - Rakefile
  - README.adoc
  - vendor # for deployment
